// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhFRZAzH1xGJl7U-_gPz8eYvQircb6D4Y',
    appId: '1:114766286967:web:34a2d7970c879bc8723672',
    messagingSenderId: '114766286967',
    projectId: 'noteapp-00',
    authDomain: 'noteapp-00.firebaseapp.com',
    storageBucket: 'noteapp-00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7pRnClLblHaFuYpjs3qIxpkeR9GrvHG0',
    appId: '1:114766286967:android:dc54c31ad661e23e723672',
    messagingSenderId: '114766286967',
    projectId: 'noteapp-00',
    storageBucket: 'noteapp-00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEpIuUC2nepf9ZxASYwe1NjJ0pmq7Bgcs',
    appId: '1:114766286967:ios:f0a9b98c1dd79161723672',
    messagingSenderId: '114766286967',
    projectId: 'noteapp-00',
    storageBucket: 'noteapp-00.appspot.com',
    iosClientId:
        '114766286967-fpkrscqec537tbk2hoan7917mb1rab5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );
}
